#Aqui tenemos al recepcionista que se encarga de recibir las peticiones y distribuirlas a los diferentes nginx que tenemos en el deployment
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: mi-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer