#Aqui defiinimos que queremos 3 replicas de nginx 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-web
  template: 
    metadata:
      labels:
        app: mi-web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html #Aqui es donde nginx va a buscar los archivos html para servirlos
      volumes:
      - name: html-volume
        configMap:
          name: web-content #Nombre del configmap que creamos 