apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-api
spec:
  replicas: 2 # ¡Queremos 2 copias de nuestra API funcionando!
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
        command: ["/bin/bash", "-c"]
        args:
          - |
            pip install redis
            /start.sh
        ports:
        - containerPort: 80
        # Aquí inyectamos las variables del ConfigMap que hicimos arriba
        envFrom:
        - configMapRef:
            name: api-config
        volumeMounts:
        - name: code-volume
          mountPath: /app/main.py
          subPath: main.py
      volumes:
      - name: code-volume
        configMap:
          name: api-code
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer # Esto nos permite verlo desde fuera del cluster
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80